// <auto-generated />
using System;
using BugReport.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BugReport.Migrations
{
    [DbContext(typeof(BugTrackerContext))]
    [Migration("20190312142925_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("BugReport.Models.ProjectItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<DateTime?>("Modified");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("ProjectItems");
                });

            modelBuilder.Entity("BugReport.Models.TaskItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<DateTime?>("Modified");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int>("Priority");

                    b.Property<int>("ProjectId");

                    b.Property<int?>("ProjectItemID");

                    b.Property<int>("Status");

                    b.HasKey("ID");

                    b.HasIndex("ProjectItemID");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("BugReport.Models.TaskItem", b =>
                {
                    b.HasOne("BugReport.Models.ProjectItem", "ProjectItem")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectItemID");
                });
#pragma warning restore 612, 618
        }
    }
}
